project-gongsimchae/gongsimchae

- src/main/resources/application.properties
- Oauth2 관련 환경설정
-
- gitignore에 추가돼서 적용이 되려는지 모르겠지만, clone 할 때 안되면 수동으로 하는수밖에 없긴합니다.
- #
> Config: Oauth2 환경설정

- src/main/resources/application.properties
- Config: Kakao Oatuh2 환경설정 삭제
- kakao Oauth2 환경설정은 필요없어서 삭제처리 했습니다.
-
- #
> Config: Kakao Oatuh2 환경설정 삭제

- src/main/resources/application.yml
- Config: redis 환경설정 추가
- redis는 6379포트에서 localhost 환경에서만 작동하도록 했습니다.
-
- #
> Config: redis 환경설정 추가

- src/main/java/techit/gongsimchae/domain/common/refreshtoken/service/RefreshTokenService.java
- src/main/java/techit/gongsimchae/domain/common/user/dto/FindIdVO.java
- src/main/java/techit/gongsimchae/domain/common/user/dto/UserFindIdReqDtoWeb.java
- src/main/java/techit/gongsimchae/domain/common/user/dto/UserFindPwReqDtoWeb.java
- src/main/java/techit/gongsimchae/domain/common/user/dto/UserJoinReqDtoWeb.java
- src/main/java/techit/gongsimchae/domain/common/user/dto/UserRespDtoWeb.java
- src/main/java/techit/gongsimchae/domain/common/user/dto/UserUpdateReqDtoWeb.java
- src/main/java/techit/gongsimchae/domain/common/user/entity/User.java
- src/main/java/techit/gongsimchae/domain/common/user/repository/UserRepository.java
- src/main/java/techit/gongsimchae/domain/common/user/service/UserService.java
- src/main/java/techit/gongsimchae/domain/mail/event/LoginIdEvent.java
- src/main/java/techit/gongsimchae/domain/mail/event/MailEventHandler.java
- src/main/java/techit/gongsimchae/domain/mail/event/PasswordEvent.java
- src/main/java/techit/gongsimchae/domain/mail/service/EmailService.java
- src/main/java/techit/gongsimchae/global/security/SecurityConfig.java
- src/main/java/techit/gongsimchae/global/security/jwt/JwtAuthorizationFilter.java
- src/main/java/techit/gongsimchae/global/util/CookieUtil.java
- src/main/java/techit/gongsimchae/web/LoginController.java
- src/main/java/techit/gongsimchae/web/UserController.java
- src/main/resources/static/css/login.css
- src/main/resources/templates/layout/header.html
- src/main/resources/templates/login/findId.html
- src/main/resources/templates/login/findIdSuccess.html
- src/main/resources/templates/login/findPw.html
- src/main/resources/templates/login/findPwSuccess.html
- src/main/resources/templates/login/login.html
- src/main/resources/templates/user/update.html
- src/test/java/techit/gongsimchae/common/LoginIdReplace.java
- src/test/java/techit/gongsimchae/domain/common/refreshtoken/service/RefreshTokenServiceTest.java
-  Feat: 아이디 찾기, 비밀번호 찾기 로직 구현
- css는 아예 손도 안댔습니다
- 쿠키를 활용한 데이터 받기는 좀 더 고민해봐야 할 문제입니다.
- 일시적인 URL을 만들어서 비밀번호를 재발급하는 로직도 만들어 보고싶지만 고도화 때 시간이 된다면 해보겠습니다
- #
>  Feat: 아이디 찾기, 비밀번호 찾기 로직 구현

- src/main/java/techit/gongsimchae/domain/admin/coupon/entity/Coupon.java
- src/main/java/techit/gongsimchae/domain/admin/coupon/repository/CouponRepository.java
- src/main/java/techit/gongsimchae/domain/admin/coupon/service/CouponService.java
- src/main/java/techit/gongsimchae/domain/admin/item/dto/ItemDto.java
- src/main/java/techit/gongsimchae/domain/admin/item/entity/Item.java
- src/main/java/techit/gongsimchae/domain/admin/item/repository/ItemRepository.java
- src/main/java/techit/gongsimchae/domain/admin/item/service/ItemService.java
- src/main/java/techit/gongsimchae/web/AdminController.java
- src/main/java/techit/gongsimchae/web/CouponController.java
- src/main/java/techit/gongsimchae/web/ItemController.java
- src/main/resources/templates/admin/admin.html
- src/main/resources/templates/admin/event/event.html
- src/main/resources/templates/admin/event/eventForm.html
- src/main/resources/templates/admin/item/item.html
- src/main/resources/templates/admin/item/itemForm.html
- 관리자 페이지에 이벤트 관리/상품 관리 링크
- 각 페이지에 이벤트 생성/삭제, 상품 생성/수정/삭제 기능 추가
- 
- 아이템 UID 등 일부 제외하고 정말 폼 작성하는 페이지만 구현했습니다.
- 보완하고 수정해야 할 부분이 많은데 일단 풀 리퀘 하고 내일 아침 회의 때 다시 얘기해봐야 할 것 같습니다.
- #
> - feat: 이벤트 생성,삭제 및 상품 생성, 수정, 삭제 구현

- src/main/resources/application.properties
> Config: properties  추가

- src/main/resources/application.yml
> Config: main yml 추가

- src/main/resources/application-dev.yml
> Config: dev yml 추가

- src/main/resources/application-prod.yml
> Config: prod yml 추가

- src/main/resources/application-test.yml
> Config: test.yml 파일 추가

- src/main/java/techit/gongsimchae/web/MyPageController.java
- src/main/resources/static/css/mypage.css
- src/main/resources/templates/mypage/orders.html
- 마이페이지의 사이드바를 구현했습니다.
- 
-
- #
> Feat: 마이페이지 사이드바 구현

- src/main/java/techit/gongsimchae/domain/portion/areas/entity/MyeondongeupArea.java
- src/main/java/techit/gongsimchae/domain/portion/areas/entity/SidoArea.java
- src/main/java/techit/gongsimchae/domain/portion/areas/entity/SigunguArea.java
- src/main/java/techit/gongsimchae/domain/portion/areas/repository/AreasRepository.java
- src/main/java/techit/gongsimchae/domain/portion/areas/repository/MyeondongeupAreaRepository.java
- src/main/java/techit/gongsimchae/domain/portion/areas/repository/SidoAreaRepository.java
- src/main/java/techit/gongsimchae/domain/portion/areas/repository/SigunguAreaRepository.java
- src/main/java/techit/gongsimchae/domain/portion/areas/service/AreasService.java
- src/main/java/techit/gongsimchae/domain/portion/areas/service/MyeondongeupAreaService.java
- src/main/java/techit/gongsimchae/domain/portion/areas/service/SidoAreaService.java
- src/main/java/techit/gongsimchae/domain/portion/areas/service/SigunguAreaService.java
- src/main/java/techit/gongsimchae/web/PortionMainController.java
- src/main/resources/static/css/portion/portioningMain.css
- src/main/resources/static/js/portion/portioningMain.js
- src/main/resources/templates/portion/myeondongeups.html
- src/main/resources/templates/portion/portioningMain.html
- src/main/resources/templates/portion/sigungus.html
- 시도, 시군구, 면동읍 지역 선택 및 태그 추가
-
- 태그 추가 후 삭제 시 시도부터 다시 선택해야 태그가 달리는 문제를 이틀 내에 해결하지 못했습니다. js 잘 다루시는 분 중 방법 아시는 분 알려주시면 수정하도록 하겠습니다
- 시도는 전국, 시군구/면동읍은 서울만 넣어놨습니다. 시도, 시군구 지역코드는 실제 지역코드입니다. 면동읍 지역코드는 너무 많아서 일단은 대충 아무 숫자나 넣어놓은 상태입니다.
- 아직 뷰만 구현한 상태로, 실제 검색은 안됩니다.
- #
> - feat: 소분 지역 선택 및 태그 추가

- src/main/java/techit/gongsimchae/domain/groupbuying/item/repository/ItemRepository.java
- src/main/java/techit/gongsimchae/domain/groupbuying/item/service/ItemService.java
- src/main/java/techit/gongsimchae/web/ItemController.java
- src/main/resources/templates/category/bestItem.html
- src/main/resources/templates/layout/navbar.html
- 신상품 부분과 다른 부분이 쿼리 부분밖에 없습니다. 크게 리뷰할 부분은 없을 것 같아요.
-
-
- #
> Feat: 베스트 페이지 뷰, 기능, 정렬 추가

- src/main/java/techit/gongsimchae/domain/common/imagefile/entity/ImageFile.java
> Fix: 깃 충돌 해결

- src/main/java/techit/gongsimchae/domain/common/imagefile/dto/ImageFileRespDto.java
- src/main/java/techit/gongsimchae/domain/common/imagefile/service/ImageS3Service.java
- src/main/java/techit/gongsimchae/domain/common/wishlist/repository/WishListRepository.java
- src/main/java/techit/gongsimchae/domain/common/wishlist/service/WishListService.java
- src/main/java/techit/gongsimchae/domain/portion/subdivision/dto/SubdivisionRespDto.java
- src/main/java/techit/gongsimchae/domain/portion/subdivision/dto/SubdivisionUpdateReqDto.java
- src/main/java/techit/gongsimchae/domain/portion/subdivision/entity/Subdivision.java
- src/main/java/techit/gongsimchae/domain/portion/subdivision/entity/SubdivisionType.java
- src/main/java/techit/gongsimchae/domain/portion/subdivision/repository/SubdivisionRepository.java
- src/main/java/techit/gongsimchae/domain/portion/subdivision/service/SubdivisionService.java
- src/main/java/techit/gongsimchae/global/security/SecurityConfig.java
- src/main/java/techit/gongsimchae/web/SubdivisionController.java
- src/main/resources/static/js/portion/subdivisionDetail.js
- src/main/resources/static/js/portion/subdivisionUpdate.js
- src/main/resources/templates/mypage/mySubdivisionList.html
- src/main/resources/templates/mypage/subdivisionJoinList.html
- src/main/resources/templates/mypage/subdivisionWishlist.html
- src/main/resources/templates/portion/subdivisionDetail.html
- src/main/resources/templates/portion/subdivisionUpdate.html
- 소분 글 수정 및 삭제 기능 구현 완료하였습니다.
- Subdivision 엔티티에 삭제 여부를 나타내는 deleteStatus 필드, 소분 글 상태를 나타내는 SubdivisionType 필드 추가해주었습니다.
- 그래서 페이지에서 삭제를 해도 완전히 삭제되지는 않고 deleteStatus 값만 바뀝니다.
- 소분 글 CRUD는 전부 구현 완료하였습니다.
- #
> Feat: 소분 글 수정 및 삭제 구현 완료

- src/main/resources/static/css/gongu.css
- src/main/resources/static/css/mypage.css
- src/main/resources/static/css/mypage/inquiryList.css
- src/main/resources/static/css/mypage/picklist.css
- src/main/resources/static/css/navbar.css
- src/main/resources/templates/home.html
- src/main/resources/templates/layout/mypage.html
- src/main/resources/templates/layout/navbar.html
- src/main/resources/templates/mypage/coupons.html
- src/main/resources/templates/mypage/inquiryForm.html
- src/main/resources/templates/mypage/inquiryList.html
- src/main/resources/templates/mypage/inquiryUpdate.html
- src/main/resources/templates/mypage/orders.html
- src/main/resources/templates/mypage/ordersDetail.html
- src/main/resources/templates/mypage/pickList.html
- src/main/resources/templates/mypage/reviews.html
- src/main/resources/templates/user/address.html
- src/main/resources/templates/user/info.html
- src/main/resources/templates/user/update.html
> Refactor: 메인 페이지 CSS수정 

- src/main/java/techit/gongsimchae/domain/common/imagefile/entity/S3VO.java
- src/main/java/techit/gongsimchae/domain/groupbuying/event/service/EventService.java
- src/main/java/techit/gongsimchae/domain/portion/subdivision/service/SubdivisionService.java
- src/main/resources/static/css/ordersDetail.css
- src/main/resources/templates/category/bestItem.html
- src/main/resources/templates/category/category.html
- src/main/resources/templates/category/newItem.html
- src/main/resources/templates/layout/navbar.html
- src/main/resources/templates/mypage/mySubdivisionList.html
- src/main/resources/templates/mypage/subdivisionJoinList.html
- src/main/resources/templates/mypage/subdivisionWishlist.html
> Fix: 버그 수정

- src/main/java/techit/gongsimchae/domain/common/imagefile/repository/ImageFileRepository.java
- src/main/java/techit/gongsimchae/domain/groupbuying/item/dto/ItemCardResDtoWeb.java
- src/main/java/techit/gongsimchae/domain/groupbuying/item/dto/ItemRespDtoWeb.java
- src/main/java/techit/gongsimchae/domain/groupbuying/item/service/ItemService.java
- src/main/java/techit/gongsimchae/web/HomeController.java
- src/main/java/techit/gongsimchae/web/ItemController.java
- src/main/resources/templates/category/bestItem.html
- src/main/resources/templates/category/category.html
- src/main/resources/templates/category/newItem.html
- src/main/resources/templates/groupbuying/itemDetails.html
- src/main/resources/templates/home.html
- src/main/resources/templates/mypage/pickList.html
- 아이템 직접 반환하는 요청 중 이미지 임시로 하드 코딩 되어 있던 부분을 Dto 반환으로 묶어 이미지 반환으로 변경했습니다.
- 
-
- #
> Refactor: 뷰에 아이템 엔티티 직접 반환에서 Dto 반환으로 변경, 이미지 추가

- build.gradle
- 서브모듈의 yml, properties 파일 제대로 가져올 수 있도록 다시 설정했습니다
-
-
- #
> Config: 서브모듈의 yml, properties 파일 제대로 가져올 수 있도록 재설정

- .gitmodules
- Config : .gitmodules 추가
-
-
- #
> Config : .gitmodules 추가

- src/main/java/techit/gongsimchae/web/WebRestController.java
> Feat: 현재 활성화된 Profile 반환

- src/main/java/techit/gongsimchae/domain/common/address/dto/AddressCreateReqDtoWeb.java
- src/main/java/techit/gongsimchae/domain/common/address/entity/Address.java
- src/main/java/techit/gongsimchae/domain/common/inquiry/repository/InquiryCustomRepositoryImpl.java
- src/main/java/techit/gongsimchae/domain/portion/subdivision/repository/SubdivisionCustomRepositoryImpl.java
- src/main/java/techit/gongsimchae/global/message/ErrorMessage.java
-  !HOTFIX: 자잘한 버그 수정 및 QueryDsl QFile이 생성되어있지 않은 문제
- 자잘하게 중복된 코드와 괄호가 없는 코드를 수정했습니다.
- generate에 QFile이 제대로 생성되어있지 않아 오류가 나는 상황이 발생했습니다.
- 만약 QueryDsl에서 Qfile어쩌고 오류가 나타난다면  Querydsl 코드들만 주석처리 하시고 return null로 하신다음에
- gradle -> build -> build 우클릭 후 run을 하셔야 됩니다
- 코드만 주석처리하는게 아니라 전체 다 주석처리 해버리시면 연관되어 있는 서비스, 컨트롤러까지 손 봐야 되기 때문에 return 만 null로 바꾸셔야 편할거에요
- #
>  !HOTFIX: 자잘한 버그 수정 및 QueryDsl QFile이 생성되어있지 않은 문제

- src/main/java/techit/gongsimchae/domain/groupbuying/category/dto/CategoryReqDtoWeb.java
- src/main/java/techit/gongsimchae/domain/groupbuying/category/entity/Category.java
- src/main/java/techit/gongsimchae/domain/groupbuying/category/repository/CategoryRepository.java
- src/main/java/techit/gongsimchae/domain/groupbuying/category/service/CategoryService.java
- src/main/java/techit/gongsimchae/global/valid/CategoryNameUnique.java
- src/main/java/techit/gongsimchae/global/valid/CategoryNameUniqueValidator.java
- src/main/java/techit/gongsimchae/web/AdminController.java
- src/main/resources/templates/admin/category/categoryList.html
- 카테고리 중복 생성 방지하는 기능을 추가했습니다.
- 어노테이션 방식으로 중복을 체크합니다.
- 작은 검증 로직 추가라 내용이 많지 않아 크게 특이사항은 없습니다.
-
- #
> Refactor: 카테고리 중복 방지 기능 추가

- src/main/java/techit/gongsimchae/domain/groupbuying/category/service/CategoryService.java
- src/main/java/techit/gongsimchae/domain/web/common/AdminController.java
- src/main/resources/templates/admin/category/categoryList.html
- 제가 모달에서 예외 처리 구현하다가 코드를 날려 먹은 것 같습니다.. 다시 작성해서 수정했습니다
-
-
- #
> Fix: 카테고리 복구 버튼 코드 재작성

- src/main/java/techit/gongsimchae/domain/web/groupbuying/ItemController.java
> Fix: 아이템 생성 시 delete 상태의 카테고리가 보이는 문제 해결

- src/main/java/techit/gongsimchae/domain/groupbuying/item/entity/Item.java
- src/main/java/techit/gongsimchae/domain/groupbuying/item/service/ItemService.java
- src/main/java/techit/gongsimchae/domain/web/groupbuying/ItemController.java
- src/main/resources/static/css/admin/item.css
- src/main/resources/templates/admin/item/item.html
- 아이템 삭제 처리 변경 
-
- 아이템 삭제 시 복구 버튼으로 변경했습니다. 아이템 삭제에 따라 수정 버튼은 숨김 처리 하였습니다.  
- #
> Refactor: 아이템 삭제 시 복구 버튼으로 변경

- src/main/java/techit/gongsimchae/domain/web/groupbuying/ItemController.java
-  Fix: 관리자 상품관리 페이징 사이즈 10으로 수정
- 상품관리 페이징 2-> 10으로 수정했습니다
-
- #
>  Fix: 관리자 상품관리 페이징 사이즈 10으로 수정

- src/main/java/techit/gongsimchae/domain/portion/notificationkeyword/entity/NotificationKeyword.java
- src/main/java/techit/gongsimchae/domain/portion/subdivision/dto/SubdivisionReqDto.java
- Fix: 제약조건 및 유효성 검사 수정
- 잘못걸려있던 제약조건 및 유효성 검사 수정했습니다.
-
- #
> Fix: 제약조건 및 유효성 검사 수정

- src/main/resources/static/css/admin/item.css
- src/main/resources/static/css/gongu.css
- src/main/resources/static/js/groupbuying/itemdetail.js
- src/main/resources/templates/admin/category/categoryList.html
- src/main/resources/templates/admin/item/item.html
- src/main/resources/templates/groupbuying/itemDetails.html
- src/main/resources/templates/home.html
- 로그인 안되어 있는 상태에서 아이템 찜이 되는 오류 수정 
- 
- 아이템 목록 일부 html, css 수정했습니다. 카테고리별 아이템, 신상품 등 아이템 목록 보이는 나머지 부분들도 수정할 예정입니다. 
- #
> Fix: 로그인 안되어 있는 상태에서 아이템 찜이 되는 오류 수정

- src/main/java/techit/gongsimchae/domain/web/common/MyPageController.java
- src/main/java/techit/gongsimchae/domain/web/groupbuying/ItemController.java
- src/main/resources/static/css/portion/portioningMain.css
- src/main/resources/static/js/groupbuying/mainnew.js
- src/main/resources/templates/groupbuying/itemDetails.html
> Fix: 로그인 시 찜 시 찜 안되는 오류 수정

- src/main/generated/techit/gongsimchae/domain/QBaseEntity.java
- src/main/java/techit/gongsimchae/web/WebRestController.java
- Fix: 현재 실행중인 profile이 제대로 안뜨는 오류 수정
-
-
- #
> Fix: 현재 실행중인 profile이 제대로 안뜨는 오류 수정

- src/main/java/techit/gongsimchae/domain/groupbuying/item/dto/ItemRespDtoWeb.java
- src/main/resources/templates/groupbuying/search.html
-  Fix: 엘라스틱 서치에 썸네일 이미지가 저장되도록 변경
- 썸네일 이미지가 저장되도록 변경했습니다
- 검색할 때 메인 css와 똑같이 나오도록 변경했습니다
-
- #
>  Fix: 엘라스틱 서치에 썸네일 이미지가 저장되도록 변경

- src/main/java/techit/gongsimchae/domain/groupbuying/orders/service/OrdersService.java
- src/main/java/techit/gongsimchae/domain/web/groupbuying/OrderController.java
- src/main/java/techit/gongsimchae/global/message/ErrorMessage.java
- src/main/resources/static/css/groupbuying/orderComplete.css
- src/main/resources/static/js/groupbuying/order.js
- src/main/resources/templates/groupbuying/orderComplete.html
> Feat: 주문 완료 페이지 구현

- src/main/java/techit/gongsimchae/global/config/ElasticsearchConfig.java
- src/main/resources/static/js/groupbuying/mainnew.js
- src/main/resources/static/js/portion/chat.js
- src/main/resources/templates/home.html
- src/main/resources/templates/portion/chatroom.html
- src/main/resources/templates/portion/portioningMain.html
- Fix: 채팅 사진 안보내는 현상수정, 공구 메인 progress바 수정
- 소분 메인 인포 삭제했습니다
- dev에서는 localhost:9200으로 할게요
- 배포용은 main에서만 하는걸로 해주세여
- 
- #
>  Fix: 채팅 사진 안보내는 현상수정, 공구 메인 progress바 수정

- src/main/java/techit/gongsimchae/domain/common/es/repository/ItemElasticRepository.java
-  Fix: 엘라스틱 서치 아이템 조회 수정
-
-
- #
>  Fix: 엘라스틱 서치 아이템 조회 수정
